//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/InputActions/UnitControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UnitControl : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UnitControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UnitControl"",
    ""maps"": [
        {
            ""name"": ""BattleMap"",
            ""id"": ""6ccc8230-cc4c-4d36-9164-05c27c519bc8"",
            ""actions"": [
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""ecb2a8a8-4d30-4df9-85ad-555eac301b8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""00a8df91-4723-4d36-8eed-923bbd61cbe7"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BattleMap
        m_BattleMap = asset.FindActionMap("BattleMap", throwIfNotFound: true);
        m_BattleMap_RightClick = m_BattleMap.FindAction("RightClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BattleMap
    private readonly InputActionMap m_BattleMap;
    private IBattleMapActions m_BattleMapActionsCallbackInterface;
    private readonly InputAction m_BattleMap_RightClick;
    public struct BattleMapActions
    {
        private @UnitControl m_Wrapper;
        public BattleMapActions(@UnitControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @RightClick => m_Wrapper.m_BattleMap_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_BattleMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BattleMapActions set) { return set.Get(); }
        public void SetCallbacks(IBattleMapActions instance)
        {
            if (m_Wrapper.m_BattleMapActionsCallbackInterface != null)
            {
                @RightClick.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnRightClick;
            }
            m_Wrapper.m_BattleMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
            }
        }
    }
    public BattleMapActions @BattleMap => new BattleMapActions(this);
    public interface IBattleMapActions
    {
        void OnRightClick(InputAction.CallbackContext context);
    }
}
